In [1]:
import numpy as np
import pandas as pd

In [3]:
iris_df = pd.read_csv("Iris.csv")

In [4]:
sepal_length_array = iris_df['sepal_length'].to_numpy()

print("First 10 values of 'sepal_length' NumPy array:")
print(sepal_length_array[:10])
print(f"Shape of the array: {sepal_length_array.shape}")

First 10 values of 'sepal_length' NumPy array:
[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9]
Shape of the array: (150,)


In [5]:
numbers = [5, 2, 8, 1, 9, 4]
print(f"Original list: {numbers}")

# Bubble sort using while loop
length = len(numbers)
has_swapped = True

while has_swapped:
    has_swapped = False
    index = 0
    while index < length - 1:
        if numbers[index] > numbers[index + 1]:
            # Swap elements
            numbers[index], numbers[index + 1] = numbers[index + 1], numbers[index]
            has_swapped = True
        index += 1
    length -= 1  # Optimization: last element is already sorted

print(f"Sorted list using while loop: {numbers}")


Original list: [5, 2, 8, 1, 9, 4]
Sorted list using while loop: [1, 2, 4, 5, 8, 9]


In [6]:
sorted_sepal_length = np.sort(sepal_length_array)

print("First 10 values of the sorted 'sepal_length' NumPy array:")
print(sorted_sepal_length[:30])
print(f"Shape of the sorted array: {sorted_sepal_length.shape}")

First 10 values of the sorted 'sepal_length' NumPy array:
[4.3 4.4 4.4 4.4 4.5 4.6 4.6 4.6 4.6 4.7 4.7 4.8 4.8 4.8 4.8 4.8 4.9 4.9
 4.9 4.9 4.9 4.9 5.  5.  5.  5.  5.  5.  5.  5. ]
Shape of the sorted array: (150,)


In [7]:
# Generate 1000x4 matrix of random floats
data = np.random.rand(1000, 4)

# Mean of each column
column_means = np.mean(data, axis=0)

# Standard deviation of each column
column_stds = np.std(data, axis=0)

print("Means:", column_means)
print("Standard Deviations:", column_stds)

Means: [0.49615572 0.50823375 0.50109201 0.49592796]
Standard Deviations: [0.28321529 0.2889877  0.29355055 0.28233879]


In [8]:
import numpy as np
from sklearn.datasets import load_iris

# Load Iris dataset
iris = load_iris()

# Create Boolean mask for Petal Length > 4.0 (Column index 2)
mask = iris.data[:, 2] > 4.0

# Filter rows using Boolean indexing
large_petals = iris.data[mask]

print("Filtered data (Petal Length > 4.0):")
print(large_petals)

Filtered data (Petal Length > 4.0):
[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [6.6 2.9 4.6 1.3]
 [5.9 3.  4.2 1.5]
 [6.1 2.9 4.7 1.4]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.9 3.2 4.8 1.8]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [6.8 3.  5.5 2.1]
 [5.7 2.5 5.  2. ]
 [5.8 2.8 5.1 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 3.  5.5 

In [9]:
# Given species array
species = np.array(['Setosa', 'Versicolor', 'Virginica', 'Setosa'])

# Encode: Setosa -> 1, Others -> 0
mask = np.where(species == 'Setosa', 1, 0)

print("Encoded Mask:")
print(mask)

Encoded Mask:
[1 0 0 1]


In [10]:
import numpy as np
from sklearn.datasets import load_iris

# Load Iris dataset
iris = load_iris()
data = iris.data.copy()   # Create a copy of the Iris array

# Manually insert NaN at index [0, 0]
data[0, 0] = np.nan

# Locate missing value using np.isnan()
missing_mask = np.isnan(data)

print("Location of missing value:")
print(missing_mask)

# Compute mean of the affected column (column 0), ignoring NaN
col_mean = np.nanmean(data[:, 0])

# Replace NaN with column mean
data[missing_mask] = col_mean

print("\nUpdated data (NaN replaced with column mean):")
print(data[:5])  # show first 5 rows for verification

Location of missing value:
[[ True False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 